title: "Fatemeh Naeinian"
description: "PhD Student | AI & Autonomous Driving"
url: "https://FatemehNaeinian.github.io"
baseurl: ""  # leave empty for username.github.io sites

author:
  name: "Fatemeh Naeinian"
  email: "fn2174@nyu.edu"
  github: "FatemehNaeinian"
  linkedin: "fatemeh-naeinian-550004204"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
